import { createServerFn } from "@tanstack/react-start";
import { requireAdmin } from "@/integrations/supabase/role-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { getAppOctokit } from "./github-app.server";
import { generateApiKey } from "./clone-api-keys.server";
import { cascadeApiKeyToRepo } from "./clone-credentials.server";
import { fireTokenWebhook } from "./token-webhooks.server";
import type { Database } from "@/integrations/supabase/types";

// Real clone provisioning. For 'fork' and 'template' methods, we actually
// create the GitHub repo via the App; for 'clone' (independent), we just
// register the row and let the operator wire up the repo manually.

type ProvisioningMethod = Database["public"]["Enums"]["provisioning_method"];

export type ProvisionCloneInput = {
  name: string;
  slug: string;
  method: ProvisioningMethod;
  targetOwner: string; // org/user that will own the new repo
  tags: string[];
  cloudflareEnabled: boolean;
  notes: string;
  moduleIds: string[];
  // Pricing tier the customer is on, and any add-ons bought on top of it.
  // Recorded at creation so entitlement reconciliation has a baseline to diff
  // against — without it, the first plan change looks like an initial sync and
  // cannot tell an upgrade from a downgrade.
  planSlug?: string | null;
  addonSlugs?: string[];
  // When true, this clone must run on its own dedicated Supabase backend.
  // The wizard enqueues backend provisioning immediately after; DB triggers
  // prevent the backend from being deleted while this flag is set.
  // (Audit finding #11.)
  isolatedTenant?: boolean;
  // Operator-assigned billing/tracking identity.
  billingUserId?: string | null;
  billingStripeCustomerId?: string | null;
  // Which hosting provider should build and serve this clone. `manual` records
  // that a person configures the target — the arrangement every clone in this
  // fleet has today — and is NOT the same as declining a deployment. Omitted
  // means "use whatever platform_hosting_config says".
  deploymentProvider?: "vercel" | "manual" | "none";
  // Idempotency key for the whole provisioning attempt. Generated by the
  // wizard once per submit; a resubmit (double-click, network retry,
  // navigation-then-back) with the same key returns the existing clone row
  // instead of creating a second GitHub repo. (Audit finding #13.)
  idempotencyKey?: string | null;
};

export type ProvisionCloneResult =
  | { ok: true; cloneId: string; githubUrl: string | null; idempotent?: boolean }
  | { ok: false; error: string };

export const provisionClone = createServerFn({ method: "POST" })
  .middleware([requireAdmin])
  .inputValidator((input: ProvisionCloneInput) => {
    if (!input?.name?.trim()) throw new Error("name is required");
    if (!input?.slug?.trim()) throw new Error("slug is required");
    if (!input?.targetOwner?.trim()) throw new Error("targetOwner is required");
    if (!["fork", "template", "clone"].includes(input.method)) {
      throw new Error("invalid method");
    }
    const trim = (v: unknown) => (typeof v === "string" ? v.trim() : "");
    return {
      ...input,
      billingUserId: trim(input.billingUserId) || null,
      billingStripeCustomerId: trim(input.billingStripeCustomerId) || null,
      idempotencyKey: trim(input.idempotencyKey) || null,
    };
  })

  .handler(async ({ data, context }): Promise<ProvisionCloneResult> => {
    const { supabase, userId } = context;

    // ─── Issue #13: idempotency short-circuit ─────────────────────────
    // If the same operator resubmits with the same key (double-click,
    // network retry, tab-switch-then-back), return the existing clone
    // instead of forking a second GitHub repo. Enforced by the partial
    // unique index on (owner_user_id, idempotency_key).
    if (data.idempotencyKey) {
      const { data: existing } = await supabase
        .from("clones")
        .select("id, github_url")
        .eq("owner_user_id", userId)
        .eq("idempotency_key", data.idempotencyKey)
        .maybeSingle();
      if (existing) {
        return {
          ok: true,
          cloneId: existing.id,
          githubUrl: existing.github_url,
          idempotent: true,
        };
      }
    }

    const { data: prime } = await supabase.from("prime_config").select("*").limit(1).maybeSingle();
    if (!prime) {
      return { ok: false, error: "Prime not configured — set it up in Settings first" };
    }

    let githubOwner = data.targetOwner;
    let githubRepo = data.slug;
    let githubUrl: string | null = null;
    let lastSyncedSha: string | null = null;

    // Real GitHub work for fork / template
    if (data.method === "fork" || data.method === "template") {
      let octokit;
      try {
        octokit = getAppOctokit();
      } catch (e) {
        return {
          ok: false,
          error: e instanceof Error ? e.message : "GitHub App not configured",
        };
      }

      try {
        if (data.method === "fork") {
          const { data: forked } = await octokit.repos.createFork({
            owner: prime.github_owner,
            repo: prime.github_repo,
            organization: data.targetOwner,
            name: data.slug,
            default_branch_only: true,
          });
          githubOwner = forked.owner.login;
          githubRepo = forked.name;
          githubUrl = forked.html_url;
        } else {
          // template
          const { data: created } = await octokit.repos.createUsingTemplate({
            template_owner: prime.github_owner,
            template_repo: prime.github_repo,
            owner: data.targetOwner,
            name: data.slug,
            private: true,
            include_all_branches: false,
            description: `Aurixa clone of ${prime.github_owner}/${prime.github_repo}`,
          });
          githubOwner = created.owner.login;
          githubRepo = created.name;
          githubUrl = created.html_url;
        }

        // Fetch HEAD so we can record last_synced_sha = baseline
        try {
          const { data: br } = await octokit.repos.getBranch({
            owner: githubOwner,
            repo: githubRepo,
            branch: prime.default_branch || "main",
          });
          lastSyncedSha = br.commit.sha;
        } catch {
          // Fork/template can take a moment to propagate; not fatal.
          lastSyncedSha = null;
        }
      } catch (e) {
        const msg = e instanceof Error ? e.message : "GitHub repo creation failed";
        return { ok: false, error: msg };
      }
    }

    // Insert the clone row
    const { data: inserted, error: insertErr } = await supabase
      .from("clones")
      .insert({
        name: data.name,
        slug: data.slug,
        tags: data.tags,
        provisioning_method: data.method,
        github_owner: githubOwner,
        github_repo: githubRepo,
        github_url: githubUrl,
        default_branch: prime.default_branch || "main",
        cloudflare_enabled: data.cloudflareEnabled,
        sync_status: "in_sync",
        last_synced_sha: lastSyncedSha,
        last_cascade_at: lastSyncedSha ? new Date().toISOString() : null,
        owner_user_id: userId,
        billing_user_id: data.billingUserId ?? null,
        billing_stripe_customer_id: data.billingStripeCustomerId ?? null,
        notes: data.notes || null,
        isolated_tenant: data.isolatedTenant === true,
        idempotency_key: data.idempotencyKey ?? null,
        entitled_plan_slug: data.planSlug ?? null,
      })
      .select()
      .single();

    if (insertErr || !inserted) {
      return { ok: false, error: insertErr?.message ?? "Clone insert failed" };
    }

    // Record any add-ons bought alongside the tier. Written as purchase rows,
    // not to `clones.purchased_addon_slugs` — that column is derived by a
    // trigger now, so writing it directly would be overwritten on the next
    // purchase change.
    if ((data.addonSlugs ?? []).length > 0) {
      await supabase.from("clone_addon_purchases").insert(
        (data.addonSlugs ?? []).map((addon_slug) => ({
          clone_id: inserted.id,
          addon_slug,
          status: "active" as const,
          source: "operator" as const,
          created_by: userId,
          notes: "Selected during clone provisioning",
        })),
      );
    }

    // Install picked modules
    if (data.moduleIds.length > 0) {
      await supabase.from("clone_modules").insert(
        data.moduleIds.map((module_id) => ({
          clone_id: inserted.id,
          module_id,
          installed_by: userId,
        })),
      );

      // ─── Scoped cascade for picked module files ──────────────────
      // Push only the file_globs from picked modules to the freshly-created
      // repo so it lands with the modules pre-populated. Fire-and-forget:
      // failure here is non-fatal — the operator can re-cascade from the UI.
      if (data.method !== "clone" && githubUrl) {
        try {
          const { data: mods } = await supabase
            .from("modules")
            .select("id, name, file_globs")
            .in("id", data.moduleIds);
          const globs = Array.from(new Set((mods ?? []).flatMap((m) => m.file_globs ?? [])));
          if (globs.length > 0) {
            const { data: ev } = await supabase
              .from("cascade_events")
              .insert({
                trigger: "manual",
                mode: "auto_merge",
                status: "pending",
                requires_approval: false,
                scope_filter: {
                  scope: "clone_provision_modules",
                  clone_ids: [inserted.id],
                  module_ids: data.moduleIds,
                  module_globs: globs,
                },
                summary: `Provision cascade · ${mods?.length ?? 0} module(s) → ${data.name}`,
                initiated_by: userId,
              })
              .select()
              .single();
            if (ev) {
              await supabase.from("cascade_results").insert({
                cascade_event_id: ev.id,
                clone_id: inserted.id,
                status: "queued" as const,
              });
              // Durable execution: the /hooks/cascade-drain worker (pg_cron
              // every minute) atomically claims pending auto_merge events and
              // runs executeCascade. This survives Cloudflare Worker request
              // termination — previously a `void (async () => ...)` invocation
              // could be killed mid-flight, leaving the fresh clone repo
              // without its module files. (Audit finding #7.)
            }
          }
        } catch (e) {
          console.error("[provisionClone] module cascade setup failed:", e);
        }
      }
    }

    // ─── Auto-issue + cascade Aurixa API key ──────────────────────────
    // Every new clone gets a Mission Control API key generated immediately
    // and committed into its own repo (`.aurixa/credentials.json`) so the
    // clone's frontend can read it at build time. Failure here is non-fatal:
    // the clone is still considered created and the operator can re-issue.
    let issuedApiKey: { raw: string; prefix: string; id: string } | null = null;
    let cascadeResult: {
      ok: boolean;
      path: string;
      commit_sha?: string | null;
      error?: string;
    } | null = null;
    try {
      const { raw, hash, prefix } = generateApiKey();
      const keyInsert = await supabaseAdmin
        .from("clone_api_keys")
        .insert({
          clone_id: inserted.id,
          label: "auto-provisioned",
          scopes: ["tokens:meter", "clones:rotate", "seats:manage"],
          key_hash: hash,
          key_prefix: prefix,
          created_by: userId,
        })
        .select("id")
        .single();
      if (!keyInsert.error && keyInsert.data) {
        issuedApiKey = { raw, prefix, id: keyInsert.data.id };
        if (data.method !== "clone" && githubUrl) {
          cascadeResult = await cascadeApiKeyToRepo({
            owner: githubOwner,
            repo: githubRepo,
            branch: prime.default_branch || "main",
            apiKey: raw,
            apiKeyPrefix: prefix,
            reason: "initial",
            metadata: { clone_id: inserted.id, clone_name: data.name },
          });
        }
        void fireTokenWebhook(
          "tokens.key.rotated",
          {
            event_reason: "initial_provision",
            clone_id: inserted.id,
            new_key_id: keyInsert.data.id,
            new_key_prefix: prefix,
            repo_cascade: cascadeResult,
          },
          inserted.id,
        );
      }
    } catch (e) {
      console.error("[provisionClone] api key auto-issue failed:", e);
    }

    // ─── Auto-sync Codex Actions secrets to the new repo ──────────────
    // The scan and remediation workflows need the model API key to run.
    // Push the secrets immediately so the clone is ready for autonomous
    // scanning and remediation from minute one. Non-fatal.
    if (data.method !== "clone" && githubUrl) {
      try {
        const { syncRepoSecrets, buildCodexRepoSecrets } =
          await import("@/server/github-secrets.server");
        const secretResult = await syncRepoSecrets({
          owner: githubOwner,
          repo: githubRepo,
          secrets: await buildCodexRepoSecrets(),
        });
        // github_secret_syncs grants only SELECT to `authenticated`; writing
        // through the request-scoped client was denied by RLS and the error
        // discarded, so provisioning never left a history row.
        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
        const { error: historyErr } = await supabaseAdmin.from("github_secret_syncs").insert({
          target_kind: "clone",
          clone_id: inserted.id,
          owner: githubOwner,
          repo: githubRepo,
          written: secretResult.written,
          skipped: secretResult.skipped,
          failed: secretResult.failed,
          ok: secretResult.ok,
          trigger_source: "auto-provision",
          triggered_by: userId,
        });
        if (historyErr) {
          console.error(
            "[provisionClone] failed to record secret sync history:",
            historyErr.message,
          );
        }
      } catch (e) {
        console.error("[provisionClone] github secret sync failed:", e);
      }
    }

    // ─── Enqueue the deployment ───────────────────────────────────────
    // The step this pipeline never had. Everything above creates a repository
    // and a backend; nothing built the clone or served it, which is why
    // `clones.deploy_url` was read in twenty places and written in none.
    //
    // Enqueue only — the wizard's submit must never block on a third party, and
    // a Cloudflare Worker request can be terminated mid-flight. The drain owns
    // every provider call. Non-fatal for the same reason the API-key cascade is:
    // the clone exists either way and the operator can retry from the clone
    // page.
    try {
      const { data: hostingCfg } = await supabaseAdmin
        .from("platform_hosting_config")
        .select("hosting_provider_slug")
        .eq("singleton", true)
        .maybeSingle();
      const requested = data.deploymentProvider ?? hostingCfg?.hosting_provider_slug ?? "manual";
      const { isVercelConfigured } = await import("@/server/hosting/vercel-client");

      // Three outcomes, and they are three different facts (see
      // deploymentState.pure): declined, served by hand, and queued. A row is
      // written for all three so the clone page can tell them apart — an absent
      // row would make "nobody asked" indistinguishable from "the worker has not
      // reached it yet".
      const status =
        requested === "none"
          ? "not_requested"
          : requested === "manual"
            ? "not_requested"
            : isVercelConfigured()
              ? "pending"
              : "pending_platform";

      const { error: deployErr } = await supabaseAdmin.from("clone_deployments").upsert(
        {
          clone_id: inserted.id,
          provider_slug: requested === "vercel" ? "vercel" : "manual",
          status,
          status_detail:
            requested === "none"
              ? "Deployment declined during provisioning."
              : requested === "manual"
                ? "Served by a manually configured target."
                : status === "pending_platform"
                  ? "No hosting provider token configured. Nothing has been attempted."
                  : null,
          requested_by: userId,
        },
        { onConflict: "clone_id" },
      );
      if (deployErr) {
        console.error("[provisionClone] deployment enqueue failed:", deployErr.message);
      }
    } catch (e) {
      console.error("[provisionClone] deployment enqueue failed:", e);
    }

    await supabase.from("audit_log").insert({
      action: "clone.created",
      entity_type: "clone",
      entity_id: inserted.id,
      actor_user_id: userId,
      metadata: {
        method: data.method,
        cloudflare: data.cloudflareEnabled,
        modules: data.moduleIds,
        github_url: githubUrl,
        api_key_prefix: issuedApiKey?.prefix ?? null,
        repo_cascade: cascadeResult,
      },
    });

    await supabase.from("notifications").insert({
      kind: "clone_created",
      severity: "success",
      title: `Clone created: ${data.name}`,
      body:
        data.method === "clone"
          ? `Registered as independent clone (no repo created)`
          : `Provisioned via ${data.method} → ${githubOwner}/${githubRepo}`,
      clone_id: inserted.id,
      url: `/clones/${inserted.id}`,
      metadata: { method: data.method, cloudflare: data.cloudflareEnabled, github_url: githubUrl },
    });

    if (issuedApiKey) {
      await supabase.from("notifications").insert({
        kind: "tokens_key_issued",
        severity: cascadeResult?.ok === false ? "warning" : "success",
        title: `API key issued for ${data.name}`,
        body: cascadeResult?.ok
          ? `Prefix ${issuedApiKey.prefix}… cascaded to ${cascadeResult.path} on ${githubOwner}/${githubRepo}.`
          : cascadeResult
            ? `Prefix ${issuedApiKey.prefix}… created but repo cascade failed: ${cascadeResult.error ?? "unknown"}. Re-cascade from the API Keys tab.`
            : `Prefix ${issuedApiKey.prefix}… created (no repo cascade — independent clone).`,
        clone_id: inserted.id,
        url: `/settings/billing`,
        metadata: {
          new_key_id: issuedApiKey.id,
          new_key_prefix: issuedApiKey.prefix,
          new_key_secret: issuedApiKey.raw,
          repo_cascade: cascadeResult,
          reason: "initial_provision",
        },
      });
    }

    return { ok: true, cloneId: inserted.id, githubUrl };
  });
