import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Build output, the Deno edge function (separate runtime, not the Vite app),
    // and large generated files that are regenerated by tooling.
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "supabase/functions/**",
      "**/routeTree.gen.ts",
      "src/integrations/supabase/types.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // Tracked as warnings (visible, non-blocking) rather than off or error:
      // legacy `any` is being reduced incrementally (Phase 3 regenerates the DB
      // types), and surfacing unused vars/expressions flags dead code without
      // turning the lint gate red on day one.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-unused-expressions": "warn",
    },
  },
  {
    // Application code deploys to Cloudflare Workers, which forbids compiling
    // WebAssembly from bytes at runtime. libsodium-wrappers does exactly that
    // on first use, which silently broke every GitHub Actions secret sync
    // with `Aborted(CompileError: ... disallowed by embedder)`. It is kept as
    // a devDependency purely as the reference implementation that
    // github-sealed-box.server.test.ts checks our pure-JS sealed box against,
    // so importing it anywhere else is an error rather than a warning.
    files: ["**/*.{ts,tsx}"],
    ignores: ["**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "libsodium-wrappers",
              message:
                "libsodium-wrappers instantiates WebAssembly at runtime, which the Workers " +
                "runtime rejects. Use sealedBoxBase64 from @/server/github-sealed-box.server.",
            },
            {
              name: "libsodium",
              message:
                "libsodium instantiates WebAssembly at runtime, which the Workers runtime " +
                "rejects. Use sealedBoxBase64 from @/server/github-sealed-box.server.",
            },
          ],
        },
      ],
    },
  },
  eslintPluginPrettier,
  {
    // Keep format drift visible without blocking feature verification. The repo
    // already treats incremental cleanup findings as warnings, and routeTree plus
    // generated Supabase types are ignored above.
    rules: { "prettier/prettier": "warn" },
  },
);
